# Generated by Django 5.2.3 on 2025-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
