# Generated by Django 5.2.3 on 2025-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0003_notificacion_cedula_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
