# Generated by Django 5.2.3 on 2025-10-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0005_alter_usuario_ciudad_alter_usuario_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PausaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('duracion', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='notificacion',
            name='pausa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sst.pausaactiva'),
        ),
    ]
