# Generated by Django 5.2.3 on 2025-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0006_pausaactiva_notificacion_pausa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='horarios',
        ),
        migrations.AddField(
            model_name='campaña',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio de la pausa', null=True),
        ),
    ]
