# Generated by Django 5.2.3 on 2025-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0007_remove_campaña_horarios_campaña_horario_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20, null=True, verbose_name='Periodicidad'),
        ),
    ]
