# Generated by Django 5.2.3 on 2025-10-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0008_alter_campaña_periodicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
