# Generated by Django 5.2.3 on 2025-10-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0009_alter_campaña_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('por_aprobacion', 'Por aprobación'), ('finalizada', 'Finalizada')], default='activa', max_length=20, verbose_name='Estado actual'),
        ),
    ]
