# Generated by Django 5.2.3 on 2025-11-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0010_alter_campaña_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanaasignada',
            name='observacion_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Observación del Administrador'),
        ),
        migrations.AlterField(
            model_name='campaña',
            name='estado',
            field=models.CharField(blank=True, choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('por_aprobacion', 'Por aprobación'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='activa', max_length=20, null=True, verbose_name='Estado actual'),
        ),
    ]
