# Generated by Django 5.2.3 on 2025-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0011_campanaasignada_observacion_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanaasignada',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
