# Generated by Django 5.2.3 on 2025-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0012_campanaasignada_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual')], max_length=20, null=True, verbose_name='Periodicidad'),
        ),
    ]
