# Generated by Django 5.2.3 on 2025-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0013_alter_campaña_periodicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanaasignada',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
