# Generated by Django 5.2.3 on 2025-11-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0014_alter_campanaasignada_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='horario_inicio',
        ),
        migrations.AlterField(
            model_name='campaña',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.codigocampaña'),
        ),
    ]
