# Generated by Django 5.2.3 on 2025-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0015_remove_campaña_horario_inicio_alter_campaña_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='estado',
            field=models.CharField(blank=True, choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('por_aprobacion', 'Por aprobación'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada')], default='activa', max_length=20, null=True, verbose_name='Estado actual'),
        ),
    ]
