# Generated by Django 5.2.3 on 2025-11-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0018_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoSSTAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='recursos_sst/')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('imagen', 'Imagen')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoSSTEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.recursosstadmin')),
            ],
        ),
    ]
