# Generated by Django 5.2.3 on 2025-11-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0019_recursosstadmin_recursosstempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
