# Generated by Django 5.2.3 on 2025-11-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0020_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='campaña',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sst.campaña'),
        ),
    ]
