# Generated by Django 5.2.3 on 2025-11-18 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0021_alter_notificacion_campaña'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
