# Generated by Django 5.2.3 on 2025-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0022_notificacion_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
