# Generated by Django 5.2.3 on 2025-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0023_mensaje_fecha_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='realizado_por',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
