# Generated by Django 5.2.3 on 2025-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0024_remove_campaña_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='rol',
        ),
        migrations.AddField(
            model_name='permiso',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='permisos', to='sst.rol'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
