# Generated by Django 5.2.3 on 2025-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0026_crear_permisos_iniciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='roles',
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='sst.permiso'),
        ),
    ]
